version: '3'

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker_files/db:/tmp/docker_files
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    entrypoint: sh
    command: -c "
      minio server /data --address ':9000' --console-address ':9001';"

  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: >
      /bin/sh -c "
      mc alias set play_with_rails http://minio:9000 minio minio123;
      mc mb --region ap-northeast-1 play_with_rails/play-with-rails;
      "

volumes:
  db_data:
    external: false
  minio_data:
    external: false
