default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  primary:
    <<: *default
    database: pwr_development
  sub_system:
    <<: *default
    database: sub_database_development

test:
  primary:
    <<: *default
    database: pwr_test
  sub_system:
    <<: *default
    database: sub_database_test

production:
  primary:
    <<: *default
    database: pwr_production
  sub_system:
    <<: *default
    database: sub_database_production
