name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_ENDPOINT: http://127.0.0.1:9000

    services:
      db:
        image: postgres:14.6
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres123
          POSTGRES_INITDB_ARGS: "-E UTF8"
          TZ: "Asia/Tokyo"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: DB Migration
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Setup MinIO
        run: |
          mkdir -p /tmp/data/play-with-rails
          docker run -d --name minio \
                     -p 9000:9000 \
                     -e "MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}" \
                     -e "MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}" \
                     -v /tmp/data:/data \
                     minio/minio server /data

      - name: Run RSpec
        run: bundle exec rspec
